version: "3"
services:
  app:
    container_name: containerize_app_1
    build:
      context: .
      dockerfile: app/Dockerfile
    hostname: app
    command: npm run watch
    image: containerize_app
    restart: always
    volumes:
    - ./app/src:/home/node/app:rw
  nginx:
    container_name: containerize_nginx_1
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "443:443" 
      - "80:80"
    image: containerize_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/files/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/files/localhost.key:/etc/ssl/private/localhost.key
      - ./nginx/external/logs:/var/log/nginx/

